// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lost_n_found/features/auth/data/models/auth_hive_model.dart';
import 'package:lost_n_found/features/batch/data/models/batch_hive_model.dart';
import 'package:lost_n_found/features/category/data/models/category_hive_model.dart';
import 'package:lost_n_found/features/item/data/models/item_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthHiveModelAdapter());
    registerAdapter(BatchHiveModelAdapter());
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(ItemHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthHiveModelAdapter());
    registerAdapter(BatchHiveModelAdapter());
    registerAdapter(CategoryHiveModelAdapter());
    registerAdapter(ItemHiveModelAdapter());
  }
}
